### ISSUE TITLE
addin

### ISSUE THREAD

**Issue by sebdalgarno** [hctfbc/shinyypr#2]
make sure adding works

**Comment by aylapear** [comment]
not sure what this is referring too

**Comment by joethorley** [comment]
These are the addins

![Screen Shot 2021-10-07 at 13 03 23](https://user-images.githubusercontent.com/613671/136454285-2ad6dd49-7108-4e24-9aa2-f4bea9c75bbf.png)

**Comment by joethorley** [comment]
It is relatively straightforward to add one for a package.
